### ISSUE TITLE
Crash in some cases when viewing vat recipes in JEI

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/theurgy#192]
```
[10:10:36] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1123) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1204) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:816) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.1.jar%23145!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.1.jar%23145!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.NeoForgeClientUserdevLaunchHandler.runService(NeoForgeClientUserdevLaunchHandler.java:23) ~[loader-4.0.1.jar%23145!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.1.jar%23145!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.2.jar%23126!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.2.jar%23126!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
Caused by: java.lang.IllegalArgumentException: TranslatableContents' arguments must be either a Component, Number, Boolean, or a String. Was given theurgy:alchemical_sulfurs/gems/abundant for jei.tooltip.recipe.tag
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.chat.contents.TranslatableContents.<init>(TranslatableContents.java:90) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.chat.Component.translatable(Component.java:160) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.library.gui.ingredients.RecipeSlot.lambda$getTooltip$2(RecipeSlot.java:149) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.library.gui.ingredients.RecipeSlot.getTooltip(RecipeSlot.java:148) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?] {}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.library.gui.ingredients.RecipeSlot.getTooltip(RecipeSlot.java:258) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.library.gui.recipes.RecipeLayout.lambda$drawOverlays$1(RecipeLayout.java:221) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.library.gui.recipes.RecipeLayout.drawOverlays(RecipeLayout.java:220) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.gui.recipes.RecipesGui.lambda$render$4(RecipesGui.java:274) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at TRANSFORMER/jei@19.0.0.1/mezz.jei.gui.recipes.RecipesGui.render(RecipesGui.java:274) ~[jei-1.21-neoforge-19.0.0.1.jar%23199!/:19.0.0.1] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.6-beta/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:406) ~[neoforge-21.0.6-beta.jar%23193!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.6-beta/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:400) ~[neoforge-21.0.6-beta.jar%23193!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1095) ~[neoforge-21.0.6-beta.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 18 more
```

**Comment by klikli-dev** [comment]
seems to be fixed in latest jei
