### ISSUE TITLE
Random disconnacts from caloric_flux_emitter follow_projectile

### ISSUE THREAD

**Issue by schindlershadow** [klikli-dev/theurgy#223]
**Describe the bug**
Getting disconnected randomly from caloric_flux_emitter follow_projectile
```
Description: Packet handling error

java.lang.IllegalStateException: Invalid entity data item type for field 10 on entity FollowProjectile['entity.theurgy.follow_projectile'/5205, l='ClientLevel', x=-18420.57, y=35.00, z=-8028.71]: old=(-18440.5, 65.5, -8050.5)(class net.minecraft.world.phys.Vec3), new=[net.minecraft.core.particles.ColorParticleOption@5bd3a823](class java.util.ArrayList)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData.assignValue(SynchedEntityData.java:125) ~[client-1.21.1-20240808.144430-srg.jar%23431!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData.assignValues(SynchedEntityData.java:115) ~[client-1.21.1-20240808.144430-srg.jar%23431!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
```

**To Reproduce**
1. Place caloric_flux_emitter connected to some block
2. wait for DC

**Expected behavior**
no DC

**Screenshots**
![image](https://github.com/user-attachments/assets/c8678b1b-e42f-497f-b93d-d662dded166e)

**System (please complete the following information):**
- Theurgy Version: theurgy-1.21.1-neoforge-1.56.0
- OS: windows 10
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/infinix-test

**Additional context**
DC log: https://pastebin.com/raw/htLrL7Qj
may be from sodium render?

sometimes crashes client after DC

**Comment by schindlershadow** [comment]
seems like some kind of incompatibility with Connectivity 
https://www.curseforge.com/minecraft/mc-mods/connectivity
havent DCed once after disabling it on client side

**Comment by klikli-dev** [comment]
@schindlershadow can you open a report on connectivity's issue page and link here?
I believe they should be able to tell us more, as they are networking experts.

Based on the error message I believe that with that mod present minecraft expects certain limitations when entities are synchronized, but a quick check of the follow projectile entity does not tell me what that may be as I just use normal neoforge stuff as far as I can see

**Comment by schindlershadow** [comment]
opened https://github.com/someaddons/connectivity/issues/103

**Comment by schindlershadow** [comment]
I am now getting this without connectivity, all players get booted from server on login with the following disconnect log for about 10 mins 

https://pastebin.com/raw/S9kpWvif

**Comment by klikli-dev** [comment]
> I am now getting this without connectivity, all players get booted from server on login with the following disconnect log for about 10 mins
> 
> https://pastebin.com/raw/S9kpWvif

I am still unable to reproduce it, but I am asking in the neoforge discord about it. I searched thereand all other instances of this error is when a mod tries to modify the entity sync data of a vanilla entity or another modded entity. So that would mean that there is still a mod in the pack that modifies entities somehow - but I am verifying with them if that is necessarily always the case.

Meanwhile, can you try if this happens if you set up a minimal pack with just theurgy + dependencies in a server + client environment? For me that is not the case.

**Comment by someaddons** [comment]
Those syncedEntityData issues are typically caused by some mod mixin additional entity data in, which can cause the data order to shift and thus the client not being able to read it in the right order. It is always a mod compat issue with one of the other mods handling syncedentitydata that way, so gotta find out which other mod it is

**Comment by schindlershadow** [comment]
so far I've noticed in SP it does not happen. maybe some server-side mod. ill keep testing

**Comment by klikli-dev** [comment]
> Those syncedEntityData issues are typically caused by some mod mixin additional entity data in, which can cause the data order to shift and thus the client not being able to read it in the right order. It is always a mod compat issue with one of the other mods handling syncedentitydata that way, so gotta find out which other mod it is

Considering this I will close this issue for now. If we find out which mod is incompatible, or that it is theurgy on its own after all please ping me to reopen
